function getConfig() { return window.APP_CONFIG || {}; }
const els = {
  authSection: document.getElementById('auth-section'), loginBtn: document.getElementById('login-btn'), logoutBtn: document.getElementById('logout-btn'),
  messageBox: document.getElementById('message-box'), memberSection: document.getElementById('member-section'), memberName: document.getElementById('member-name'), memberAvatar: document.getElementById('member-avatar'),
  adminLayout: document.getElementById('admin-layout'), campaignList: document.getElementById('campaign-list'), newCampaignBtn: document.getElementById('new-campaign-btn'), refreshCampaignsBtn: document.getElementById('refresh-campaigns-btn'),
  editorTitle: document.getElementById('editor-title'), campaignStatusPill: document.getElementById('campaign-status-pill'), campaignId: document.getElementById('campaign-id'), campaignTitle: document.getElementById('campaign-title'),
  pointsPerDraw: document.getElementById('points-per-draw'), totalTickets: document.getElementById('total-tickets'), maxDrawPerOrder: document.getElementById('max-draw-per-order'), turnHoldSeconds: document.getElementById('turn-hold-seconds'),
  coverImageUrl: document.getElementById('cover-image-url'), startsAt: document.getElementById('starts-at'), endsAt: document.getElementById('ends-at'), campaignDescription: document.getElementById('campaign-description'),
  prizeRows: document.getElementById('prize-rows'), addPrizeRowBtn: document.getElementById('add-prize-row-btn'), prizeSummary: document.getElementById('prize-summary'),
  saveCampaignBtn: document.getElementById('save-campaign-btn'), publishCampaignBtn: document.getElementById('publish-campaign-btn'), pauseCampaignBtn: document.getElementById('pause-campaign-btn'), resumeCampaignBtn: document.getElementById('resume-campaign-btn'), endCampaignBtn: document.getElementById('end-campaign-btn'),
  refreshOrdersBtn: document.getElementById('refresh-orders-btn'), orderList: document.getElementById('order-list'),
  memberSearchInput: document.getElementById('member-search-input'), memberSearchBtn: document.getElementById('member-search-btn'), memberSearchResults: document.getElementById('member-search-results'),
  grantMemberId: document.getElementById('grant-member-id'), grantPoints: document.getElementById('grant-points'), grantReason: document.getElementById('grant-reason'), grantPointsBtn: document.getElementById('grant-points-btn'),
  deductMemberId: document.getElementById('deduct-member-id'), deductPoints: document.getElementById('deduct-points'), deductReason: document.getElementById('deduct-reason'), deductPointsBtn: document.getElementById('deduct-points-btn'),
};
const state = { accessToken: null, pending: new Set(), campaigns: [], currentCampaign: null, orders: [] };
function normalizeError(err, fallback='發生錯誤'){ if(err==null)return fallback; if(typeof err==='string')return err; if(err instanceof Error)return err.message||fallback; if(typeof err==='object')return err.message||err.error||fallback; return String(err); }
function escapeHtml(value){ return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
function showMessage(message,isError=false){ const text=typeof message==='string'?message:normalizeError(message); if(!text){els.messageBox.style.display='none';return;} els.messageBox.textContent=text; els.messageBox.style.display='block'; els.messageBox.className=isError?'message error':'message success'; }
function clearMessage(){ showMessage(''); }
function setButtonLoading(button,isLoading,loadingText='處理中...'){ if(!button)return; if(!button.dataset.originalText)button.dataset.originalText=button.textContent||''; button.disabled=isLoading; button.textContent=isLoading?loadingText:button.dataset.originalText; }
function startPending(key){ if(state.pending.has(key)) throw new Error('上一個操作尚未完成'); state.pending.add(key); }
function endPending(key){ state.pending.delete(key); }
function getCleanAppUrl(){ return `${window.location.origin}${window.location.pathname}`; }
async function callApi(action,payload={}){ const config=getConfig(); const res=await fetch(`${config.supabaseUrl}/functions/v1/${config.apiFunctionName}`,{method:'POST',headers:{'Content-Type':'application/json',apikey:config.supabaseAnonKey},body:JSON.stringify({action,accessToken:state.accessToken,...payload})}); const text=await res.text(); let data={}; try{data=text?JSON.parse(text):{}}catch{data={message:text}} if(!res.ok||data.ok===false) throw data; return data; }
function makeRequestId(prefix){ return window.crypto?.randomUUID ? `${prefix}-${window.crypto.randomUUID()}` : `${prefix}-${Date.now()}`; }
function toLocalInputValue(value){ if(!value) return ''; const d=new Date(value); const pad=(n)=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }
function toIsoOrNull(value){ if(!value) return null; const d=new Date(value); return Number.isNaN(d.getTime()) ? null : d.toISOString(); }
function resetEditor(){ state.currentCampaign=null; els.editorTitle.textContent='新增草稿'; els.campaignStatusPill.textContent='draft'; els.campaignId.value=''; els.campaignTitle.value=''; els.pointsPerDraw.value=''; els.totalTickets.value=''; els.maxDrawPerOrder.value='1'; els.turnHoldSeconds.value='30'; els.coverImageUrl.value=''; els.startsAt.value=''; els.endsAt.value=''; els.campaignDescription.value=''; els.orderList.innerHTML='<div class="empty-state">尚未選擇活動</div>'; els.prizeRows.innerHTML=''; addPrizeRow(); addPrizeRow(); addPrizeRow(); updatePrizeSummary(); }
function addPrizeRow(prize={}){ const row=document.createElement('div'); row.className='prize-row'; row.innerHTML=`<input class="input prize-code" placeholder="代號，例如 A賞" value="${escapeHtml(prize.prize_code||'')}"><input class="input prize-name" placeholder="獎項名稱" value="${escapeHtml(prize.prize_name||'')}"><input class="input prize-qty" type="number" min="1" step="1" placeholder="數量" value="${escapeHtml(prize.total_quantity||'1')}"><input class="input prize-order" type="number" min="0" step="1" placeholder="排序" value="${escapeHtml(prize.display_order||'0')}"><input class="input prize-image" placeholder="圖片 URL" value="${escapeHtml(prize.prize_image_url||'')}"><button class="btn btn-danger prize-remove-btn" type="button">刪除</button>`; row.querySelector('.prize-remove-btn').addEventListener('click',()=>{ row.remove(); updatePrizeSummary(); }); row.querySelectorAll('input').forEach((input)=>input.addEventListener('input',updatePrizeSummary)); els.prizeRows.appendChild(row); updatePrizeSummary(); }
function collectPrizes(){ return [...els.prizeRows.querySelectorAll('.prize-row')].map((row)=>({ prize_code: row.querySelector('.prize-code').value.trim(), prize_name: row.querySelector('.prize-name').value.trim(), total_quantity: Number(row.querySelector('.prize-qty').value||0), display_order: Number(row.querySelector('.prize-order').value||0), prize_image_url: row.querySelector('.prize-image').value.trim() || null })).filter((p)=>p.prize_code || p.prize_name || p.total_quantity); }
function updatePrizeSummary(){ const totalTickets=Number(els.totalTickets.value||0); const prizeTotal=collectPrizes().reduce((sum,p)=>sum+(Number(p.total_quantity)||0),0); els.prizeSummary.textContent=`獎項總數目前 ${prizeTotal}，總籤數 ${totalTickets}。兩者必須相等。`; els.prizeSummary.style.color = prizeTotal === totalTickets && totalTickets > 0 ? '#198754' : '#cb3a3a'; }
function renderCampaignList(){ if(!state.campaigns.length){ els.campaignList.innerHTML='<div class="empty-state">目前沒有活動</div>'; return; } els.campaignList.innerHTML=state.campaigns.map((c)=>`<button class="campaign-list-item ${state.currentCampaign?.campaign?.id===c.id?'active':''}" type="button" data-id="${c.id}"><div class="campaign-list-title">${escapeHtml(c.title)}</div><div class="campaign-list-meta">${escapeHtml(c.status)} ・ ${escapeHtml(c.remaining_tickets)} / ${escapeHtml(c.total_tickets)}</div></button>`).join(''); els.campaignList.querySelectorAll('.campaign-list-item').forEach((btn)=>btn.addEventListener('click',()=>loadCampaignDetail(btn.dataset.id))); }
function fillEditor(detail){ const c=detail.campaign; state.currentCampaign=detail; els.editorTitle.textContent=c.title || '編輯活動'; els.campaignStatusPill.textContent=c.status || 'draft'; els.campaignId.value=String(c.id||''); els.campaignTitle.value=c.title||''; els.pointsPerDraw.value=String(c.points_per_draw||''); els.totalTickets.value=String(c.total_tickets||''); els.maxDrawPerOrder.value=String(c.max_draw_per_order||''); els.turnHoldSeconds.value=String(c.turn_hold_seconds || c.reserve_seconds || 30); els.coverImageUrl.value=c.cover_image_url||''; els.startsAt.value=toLocalInputValue(c.starts_at); els.endsAt.value=toLocalInputValue(c.ends_at); els.campaignDescription.value=c.description||''; els.prizeRows.innerHTML=''; (detail.prizes||[]).forEach(addPrizeRow); if(!(detail.prizes||[]).length){ addPrizeRow(); } updatePrizeSummary(); renderOrders(state.orders || []); }
function renderOrders(orders){ if(!orders.length){ els.orderList.innerHTML='<div class="empty-state">目前沒有抽獎紀錄</div>'; return; } els.orderList.innerHTML=orders.map((o)=>`<div class="list-item list-item-stack"><div><div class="list-title">${escapeHtml(o.member_nickname || o.member_id)}</div><div class="list-subtitle">${new Date(o.created_at).toLocaleString('zh-TW')} ・ 抽 ${escapeHtml(o.draw_count)} 張 ・ 花費 ${escapeHtml(o.points_spent)} 點</div><div class="list-subtitle">結果：${escapeHtml((o.results||[]).map((r)=>`${r.prize_code || ''} ${r.prize_name || ''}`.trim()).join('、') || '—')}</div></div></div>`).join(''); }
function renderSearchResults(members){ if(!members.length){ els.memberSearchResults.innerHTML='<div class="empty-state">找不到符合的會員</div>'; return; } els.memberSearchResults.innerHTML=members.map((m)=>`<div class="list-item list-item-stack"><div><div class="list-title">${escapeHtml(m.nickname || m.display_name)}</div><div class="list-subtitle">ID：${escapeHtml(m.id)} ・ 目前 ${escapeHtml(m.current_points ?? 0)} 點</div></div><div class="admin-chip-row"><button class="btn btn-secondary select-member-btn" type="button" data-member-id="${escapeHtml(m.id)}">帶入</button></div></div>`).join(''); els.memberSearchResults.querySelectorAll('.select-member-btn').forEach((btn)=>btn.addEventListener('click',()=>{ els.grantMemberId.value=btn.dataset.memberId||''; els.deductMemberId.value=btn.dataset.memberId||''; showMessage('已帶入會員 ID'); })); }
async function loadCampaigns(){ const data = await callApi('admin_list_kuji_campaigns'); state.campaigns = data.campaigns || []; renderCampaignList(); }
async function loadCampaignDetail(campaignId){ const detail = await callApi('admin_get_kuji_campaign_detail', { campaignId: Number(campaignId) }); const orders = await callApi('admin_get_kuji_orders', { campaignId: Number(campaignId) }); state.orders = orders.orders || []; fillEditor(detail); renderCampaignList(); }
async function saveCampaign(){ const key='saveCampaign'; try{ startPending(key); setButtonLoading(els.saveCampaignBtn,true,'儲存中...'); clearMessage(); const prizes=collectPrizes(); const payload={ campaignId: els.campaignId.value.trim() ? Number(els.campaignId.value.trim()) : null, title: els.campaignTitle.value.trim(), description: els.campaignDescription.value.trim(), coverImageUrl: els.coverImageUrl.value.trim(), pointsPerDraw: Number(els.pointsPerDraw.value||0), totalTickets: Number(els.totalTickets.value||0), maxDrawPerOrder: Number(els.maxDrawPerOrder.value||0), turnHoldSeconds: Number(els.turnHoldSeconds.value||0), startsAt: toIsoOrNull(els.startsAt.value), endsAt: toIsoOrNull(els.endsAt.value), prizes }; const result=await callApi('admin_save_kuji_campaign',payload); showMessage(result.message || '草稿已儲存'); await loadCampaigns(); if(result.campaignId) await loadCampaignDetail(result.campaignId); } catch(error){ showMessage(normalizeError(error,'儲存草稿失敗'),true); } finally { endPending(key); setButtonLoading(els.saveCampaignBtn,false); } }
async function changeStatus(status, button){ const id=Number(els.campaignId.value||0); if(!id) { showMessage('請先選擇或建立活動', true); return; } const key=`status:${status}`; try{ startPending(key); setButtonLoading(button,true,'處理中...'); clearMessage(); const action = status==='active' ? 'admin_publish_kuji_campaign' : 'admin_change_kuji_campaign_status'; const payload = status==='active' ? { campaignId:id } : { campaignId:id, status }; const result = await callApi(action,payload); showMessage(result.message || '活動狀態已更新'); await loadCampaigns(); await loadCampaignDetail(id); } catch(error){ showMessage(normalizeError(error,'更新活動狀態失敗'),true);} finally { endPending(key); setButtonLoading(button,false); } }
async function searchMembers(){ const key='searchMembers'; try{ startPending(key); setButtonLoading(els.memberSearchBtn,true,'搜尋中...'); const data=await callApi('search_members',{keyword:els.memberSearchInput.value.trim()}); renderSearchResults(data.members||[]);} catch(error){ showMessage(normalizeError(error,'搜尋會員失敗'),true);} finally { endPending(key); setButtonLoading(els.memberSearchBtn,false); } }
async function grantPoints(){ const key='grantPoints'; try{ startPending(key); setButtonLoading(els.grantPointsBtn,true,'加點中...'); const result=await callApi('grant_points',{ memberId: els.grantMemberId.value.trim(), points: Number(els.grantPoints.value||0), reason: els.grantReason.value.trim(), requestId: makeRequestId('grant')}); showMessage(result.message||'加點成功'); els.grantPoints.value=''; els.grantReason.value=''; } catch(error){ showMessage(normalizeError(error,'加點失敗'),true);} finally { endPending(key); setButtonLoading(els.grantPointsBtn,false);} }
async function deductPoints(){ const key='deductPoints'; try{ startPending(key); setButtonLoading(els.deductPointsBtn,true,'扣點中...'); const result=await callApi('deduct_points',{ memberId: els.deductMemberId.value.trim(), points: Number(els.deductPoints.value||0), reason: els.deductReason.value.trim(), requestId: makeRequestId('deduct')}); showMessage(result.message||'扣點成功'); els.deductPoints.value=''; els.deductReason.value=''; } catch(error){ showMessage(normalizeError(error,'扣點失敗'),true);} finally { endPending(key); setButtonLoading(els.deductPointsBtn,false);} }
async function bootstrap(){ try{ const config=getConfig(); if(!config.liffId||!config.supabaseUrl||!config.supabaseAnonKey||!config.apiFunctionName) throw new Error('請先設定 config.js'); await liff.init({ liffId: config.liffId, withLoginOnExternalBrowser: false }); if(!liff.isLoggedIn()){ return; } state.accessToken=liff.getAccessToken(); const dashboard=await callApi('login'); if(!dashboard.member?.is_admin){ throw new Error('你不是管理員'); } els.authSection.style.display='none'; els.memberSection.style.display='block'; els.adminLayout.style.display='grid'; els.memberName.textContent = dashboard.member.nickname || dashboard.member.display_name || '管理員'; els.memberAvatar.src = dashboard.member.avatar_url || 'https://placehold.co/96x96?text=Admin'; await loadCampaigns(); resetEditor(); } catch(error){ showMessage(normalizeError(error,'初始化失敗'),true); } }
function signIn(){ if(!liff.isLoggedIn()){ liff.login({ redirectUri: getCleanAppUrl() }); return; } bootstrap(); }
function signOut(){ if(window.liff && liff.isLoggedIn()) liff.logout(); window.location.href='./index.html'; }
els.loginBtn?.addEventListener('click',signIn); els.logoutBtn?.addEventListener('click',signOut); els.newCampaignBtn?.addEventListener('click', resetEditor); els.refreshCampaignsBtn?.addEventListener('click', loadCampaigns); els.addPrizeRowBtn?.addEventListener('click', ()=>addPrizeRow()); els.totalTickets?.addEventListener('input', updatePrizeSummary); els.saveCampaignBtn?.addEventListener('click', saveCampaign); els.publishCampaignBtn?.addEventListener('click', ()=>changeStatus('active', els.publishCampaignBtn)); els.pauseCampaignBtn?.addEventListener('click', ()=>changeStatus('paused', els.pauseCampaignBtn)); els.resumeCampaignBtn?.addEventListener('click', ()=>changeStatus('active', els.resumeCampaignBtn)); els.endCampaignBtn?.addEventListener('click', ()=>changeStatus('ended', els.endCampaignBtn)); els.refreshOrdersBtn?.addEventListener('click', ()=>{ if(els.campaignId.value) loadCampaignDetail(Number(els.campaignId.value)); }); els.memberSearchBtn?.addEventListener('click', searchMembers); els.grantPointsBtn?.addEventListener('click', grantPoints); els.deductPointsBtn?.addEventListener('click', deductPoints); bootstrap();
